# Generated by Django 4.1.6 on 2023-04-07 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=60)),
                ('domestic_college', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mnemonic', models.CharField(max_length=30)),
                ('course_number', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifcation', models.CharField(blank=True, choices=[('1', 'transfer')], max_length=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.coursetransfer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=20)),
                ('course_number', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.externalcollege')),
            ],
        ),
        migrations.AddField(
            model_name='coursetransfer',
            name='external_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.externalcourse'),
        ),
        migrations.AddField(
            model_name='coursetransfer',
            name='internal_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.internalcourse'),
        ),
    ]
