# Generated by Django 4.1.6 on 2023-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0002_remove_course_text_course_catalog_nbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='catalog_nbr',
            field=models.CharField(default='b', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_section',
            field=models.CharField(default='c', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='descr',
            field=models.CharField(default='d', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
