# Generated by Django 4.1.6 on 2023-03-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0003_alter_course_catalog_nbr_alter_course_class_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=60)),
                ('domestic_college', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=30)),
                ('course_number', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=30)),
                ('course_number', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=60)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.externalcollege')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('external_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.externalcourse')),
                ('internal_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.internalcourse')),
            ],
        ),
    ]
